### ISSUE TITLE
Channel Join Error when set up with docker-compose

### ISSUE THREAD

**Issue by kkweon** [phoenixframework/phoenix#2564]
Thanks for creating Phoenix.
I have a little issue with docker-compose.
I am not really sure what is causing this, but it's reproducibile hence the issue.

### Environment (Docker setup is also same as this; see below)

* Elixir version (elixir -v): Elixir 1.5.2
* Phoenix version (mix deps): 
```
phoenix 1.3.0 (Hex package) (mix)
locked at 1.3.0 (phoenix) 1c01124c
ok
```

* NodeJS version (node -v): v8.7.0
* NPM version (npm -v): 5.4.2
* Operating system: 
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

### Expected behavior
1. Create a project and yes to all
```
mix phx.new todo
```
2. Change the database setting in `dev.exs`
```elixir
config :todo, Todo.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: (case System.get_env("DB_USERNAME") do
              nil -> "postgres"
              val -> val
            end),
  password: (case System.get_env("DB_PASSWORD") do
              nil -> "postgres"
              val -> val
            end),
  database: (case System.get_env("DB_NAME") do
              nil -> "todo_dev"
              val -> val
            end),
  hostname: (case System.get_env("DB_HOST") do
              nil -> "localhost"
              val -> val
            end),
  pool_size: 10
```
3. Create `docker-compose.yml` (dockerfile of the image: [kkweon/phoenix](https://hub.docker.com/r/kkweon/phoenix/~/dockerfile/))
```yaml
version: "3.1"

services:
  web:
    image: kkweon/phoenix:latest
    ports:
      - "4000:4000"
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: todo_dev
      DB_HOST: db
    volumes:
      - .:/code
    depends_on:
      - db

    command: ["mix", "phx.server"]

  db:
    image: postgres:10.0
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
```
4. Set up dependencies
```bash
docker-compose run web mix deps.get
docker-compose run web mix compile
docker-compose run web mix ecto.create
```
and
```bash
docker-compose run web bash
```

```bash
# inside of container
cd assets && npm i
exit
```
5. Run and go to http://localhost:4000
```bash
docker-compose up
```
6. I expect it to run without any runtime error
However,
### Actual behavior
I am getting the following error, but can't figure out what causing it since all I have done was to set up a scaffold through `mix phx.new`

Thank you in advance.

```
web_1  | [error] an exception was raised:
web_1  |     ** (RuntimeError) Channel join is expected to return one of:
web_1  | 
web_1  |     {:ok, Socket.t} |
web_1  |     {:ok, reply :: map, Socket.t} |
web_1  |     {:error, reply :: map}
web_1  | 
web_1  | got :ignore
web_1  | 
web_1  |         (phoenix) lib/phoenix/channel/server.ex:197: Phoenix.Channel.Server.init/1
web_1  |         (stdlib) gen_server.erl:365: :gen_server.init_it/2
web_1  |         (stdlib) gen_server.erl:333: :gen_server.init_it/6
web_1  |         (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```
