### ISSUE TITLE
Junk in CSS files emit no warnings in development

### ISSUE THREAD

**Issue by sodapopcan** [phoenixframework/phoenix#5222]
### Environment

* Elixir version (elixir -v): `1.14.2`
* Phoenix version (mix deps): `1.17.0-rc2`
* Operating system: 'macos 13.1 (22C65)`

It's quite possible this is not a bug but as it stands, no warnings are emitted in development when there is junk in a css file:

### Expected behavior

```css
/* assets/css/app.css */
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";

// I am not a CSS comment, I am a JS comment

I am some other random text

.valid-css {
  font-weight: bold;
}
```

Since we would get errors in our dev log if, say, that `.valid-css` selector was missing a closing brace, I expected (maybe erroneously so) that the above would emit warnings, but it does not.

### Actual behavior

The above example compiles, silently and successfully in development.  However, it _does_ fail when running `$ mix assets.deploy`.

If the answer is to use a CSS linter, that's cool, but I thought I would report it regardless.
